### ISSUE TITLE
[lua-monitoring] Find out ip address information of each interface

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/lua-monitoring#1]
This issue depends on https://github.com/openwisp/openwisp-monitoring/issues/30.

In this script:
https://github.com/openwisp/lua-monitoring/blob/master/netjson-monitoring.lua

For each monitored interface, we have to find out the ip addresses.
Once we get the list of IP, for each ip we can check the configuration of that interface to see if any static address is configured, and find out if the IP we got matches the static IP configured, if yes, that's a static address and we'll flag it as such, otherwise it's most probably an address got in DHCP client mode or manually configured, we can further check the configuration to see if the interface is flagged as proto dhcp, if yes we'll flag the address as dhcp, otherwise we'll flag it as static.

**Comment by nepython** [comment]
@nemesisdesign, shall I create a PR for `netjson-monitoring-wan.lua` or `netjson-monitoring.lua`. Well, I find both to be very similar :smiley:

**Comment by nemesisdesign** [comment]
netjson-monitoring.lua, I'll proceed to merge the two later
