### ISSUE TITLE
Document how to install

### ISSUE THREAD

**Issue by PabloCastellano** [openwisp/lua-monitoring#10]
We are now using this template: https://gist.github.com/nemesisdesign/cb005dc80a75536cf8537105c3038a71

Steps:

1. Create template in admin page
2. Mark "enable by default"
3. Associate a openwisp device

Also document how to add the template to an already registered device

**Comment by pniaps** [comment]
After installing in the device with that instructions, the command `openwisp-monitoring` does not works on the device if i dont do `opkg update && opkg install lua-cjson`

**Comment by nemesisdesign** [comment]
@pniaps also `rpcd-mod-iwinfo` is required for getting wifi data

**Comment by pniaps** [comment]
I tested on a clean **OpenWrt 19.07.3** image. I guess a new build will require more stuff, for example curl.

**Comment by nemesisdesign** [comment]
It's being solved by https://github.com/openwisp/openwisp-monitoring/pull/258.
Once we move on with packaging these scripts as an openwrt package we'll need a proper readme, but I'm closing this now to avoid wasting time of new contributors that are looking for issues to work on.
