### ISSUE TITLE
[lua-monitoring] Monitor addresses of all interfaces by default

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/lua-monitoring#12]
Monitor addresses of all interfaces by default, but do not include traffic statistics unless explicitly configured. 

I also want to make the monitoring information regarding addresses more complete by using:

```lua
nixio = require('nixio')
cjson = require('cjson')
print(cjson.encode(nixio.getifaddrs()))
```

Because `ubus call network.interface dump` only gives partial information, although it's very useful as well, so I think I will try to merge the two.

Possible new algorithm:

- call `ubus call network.interface dump`, build a dictionary of all the interfaces and their addresses
- call `nixio.getifaddrs()`, update the dictionary created previously and add only new information
- for each interface included in the list of interfaces passed in the first argument to [netjson-monitoring.lua](https://github.com/openwisp/lua-monitoring/blob/master/netjson-monitoring.lua), call also `ubus call network.device status '{"name": "<NAME>"}'` to get additional information and traffic statistics
- prepare the netjson output, including statistic/traffic information only for the interfaces specified by configuration

**Comment by PabloCastellano** [comment]
@nemesisdesign How do you want to specify if statistic/traffic information should be included? Maybe an argument when calling the lua script?

**Comment by PabloCastellano** [comment]
Unfortunately nixio seems to not return the protocol, either static or dhcp.

This is an example of an interface with a dhcp assigned IP:

```
  {
    "netmask": "255.255.255.0",
    "data": {},
    "flags": {
      "broadcast": true,
      "promisc": false,
      "up": true,
      "loopback": false,
      "noarp": false,
      "multicast": true,
      "pointtopoint": false
    },
    "addr": "192.168.1.80",
    "prefix": 24,
    "family": "inet",
    "dstaddr": "192.168.1.255",
    "broadaddr": "192.168.1.255",
    "name": "eth0.2"
  },
```

On the other hand, what information do you want to include from `ubus call network.device status`? Here is another example of the output:

```
# ubus call network.device status '{"name": "eth0.2"}'
{
	"external": false,
	"present": true,
	"type": "VLAN",
	"up": true,
	"carrier": true,
	"mtu": 1500,
	"mtu6": 1500,
	"macaddr": "94:83:c4:02:c2:bf",
	"txqueuelen": 1000,
	"ipv6": true,
	"promisc": false,
	"rpfilter": 0,
	"acceptlocal": false,
	"igmpversion": 0,
	"mldversion": 0,
	"neigh4reachabletime": 30000,
	"neigh6reachabletime": 30000,
	"neigh4gcstaletime": 60,
	"neigh6gcstaletime": 60,
	"neigh4locktime": 100,
	"dadtransmits": 1,
	"multicast": true,
	"sendredirects": true,
	"statistics": {
		"collisions": 0,
		"rx_frame_errors": 0,
		"tx_compressed": 0,
		"multicast": 47889,
		"rx_length_errors": 0,
		"tx_dropped": 0,
		"rx_bytes": 8548130,
		"rx_missed_errors": 0,
		"tx_errors": 0,
		"rx_compressed": 0,
		"rx_over_errors": 0,
		"tx_fifo_errors": 0,
		"rx_crc_errors": 0,
		"rx_packets": 70011,
		"tx_heartbeat_errors": 0,
		"rx_dropped": 620,
		"tx_aborted_errors": 0,
		"tx_packets": 23265,
		"rx_errors": 0,
		"tx_bytes": 5362278,
		"tx_window_errors": 0,
		"rx_fifo_errors": 0,
		"tx_carrier_errors": 0
	}
}
```
