### ISSUE TITLE
[change] Switch to iwinfo to get associated wifi clients

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/lua-monitoring#21]
The current method we use to get clients associated to a WiFi interface only works for access point mode, it doesn't work for `mesh` (802.11s), an most probably also not for adhoc mode.

I verified that `ubus call iwinfo assoclist '{"device": "<interface_name>"}'` works also in 802.11s, so we can switch to this instead.

**Comment by R9295** [comment]
@nemesisdesign 
It appears that ``iwinfo`` isn't providing the required data for backward compatibility with ``assoclist``
I also cannot verify if I have to take the ``ht`` and ``vht`` from either ``rx`` or ``tx`` as ubus output for hostapd & iwinfo both say ``false`` (maybe you can help here)

Also checked the [other calls](https://openwrt.org/docs/guide-developer/ubus/iwinfo) but they don't provide the values needed

Running OpenWRT 19.07-5
Here's what I have transcribed:
```
 [1] = { 
    ["wps"] = false, --- "WiFi Protected Setup" Not present in iwinfo
    ["wds"] = false, --- "Wireless Distribution System" Not present in iwinfo
    ["ht"] = false, -- rx or tx?
    ["mac"] = "ce:92:cd:37:27:f6", --- same in iwinfo
    ["rrm"] = { [1] = 0,[2] = 0,[3] = 0,[4] = 0,[5] = 0,} , --- "Radio Resource Management" Not present in iwinfo
    ["preauth"] = false, --- ?
    ["assoc"] = true,  --- ?
    ["authorized"] = true, --- same in iwinfo (but gives opposite result)
    ["vht"] = false, --- rx or tx?
    ["wmm"] = false, --- "wme" in iwinfo
    ["aid"] = 0, ---  "Association ID" don't think it's there in iwinfo
    ["mfp"] = false, --- same in iwinfo
    ["auth"] = true  --- "authenticated" in iwinfo
   }
```

My ``iwinfo`` output:
```
    {
      "mac": "............",
      "signal": -69,
      "signal_avg": 0,
      "noise": 0,
      "inactive": 0,
      "connected_time": 56,
      "thr": 0,
      "authorized": false,
      "authenticated": true,
      "preamble": "long",
      "wme": true,
      "mfp": false,
      "tdls": false,
      "mesh llid": 0,
      "mesh plid": 0,
      "mesh plink": "",
      "mesh local PS": "",
      "mesh peer PS": "",
      "mesh non-peer PS": "",
      "rx": {
        "drop_misc": 0,
        "packets": 1233,
        "bytes": 296978,
        "ht": false,
        "vht": false,
        "mhz": 20,
        "rate": 24000
      },
      "tx": {
        "failed": 15,
        "retries": 0,
        "packets": 973,
        "bytes": 374298,
        "ht": false,
        "vht": false,
        "mhz": 20,
        "rate": 72200
      }
    }
```
My ``hostapd`` output
```
 {
    "e0:bd:84:50:1e:4b": {
      "auth": true,
      "assoc": true,
      "authorized": true,
      "preauth": false,
      "wds": false,
      "wmm": false,
      "ht": false,
      "vht": false,
      "wps": false,
      "mfp": false,
      "rrm": [0, 0, 0, 0, 0], 
      "aid": 0
    }
```

**Comment by nemesisdesign** [comment]
Thanks for your summary @R9295!

I think we could use iwnfo only for mesh interfaces and keep hostapd for access point interfaces since it gives us some information that can be useful.

See below for more info and let me know if all is clear.

> @nemesisdesign
> It appears that `iwinfo` isn't providing the required data for backward compatibility with `hostapd`
> I also cannot verify if I have to take the `ht` and `vht` from either `rx` or `tx` as ubus output for hostapd & iwinfo both say `false` (maybe you can help here).

I tested on a device and I can see there's no difference between rx and tx,
they're either both true or both false.

...

> Here's what I have transcribed:
> 
> ```
>  [1] = { 
>     ["wps"] = false, --- "WiFi Protected Setup" Not present in iwinfo

ok, we can skip this for the mesh output (also because WPS doesn't make sense for mesh)

>     ["wds"] = false, --- "Wireless Distribution System" Not present in iwinfo

ok, we can skip this for the mesh output (also because WDS doesn't make sense for mesh)

>     ["ht"] = false, -- rx or tx?

take any

>     ["mac"] = "ce:92:cd:37:27:f6", --- same in iwinfo

good

>     ["rrm"] = { [1] = 0,[2] = 0,[3] = 0,[4] = 0,[5] = 0,} , --- "Radio Resource Management" Not present in iwinfo

let's skip it for mesh interfaces

>     ["preauth"] = false, --- ?

pre-authentication, should be relevant only for 802.1x

>     ["assoc"] = true,  --- ?

should mean associated

>     ["authorized"] = true, --- same in iwinfo (but gives opposite result)

I get the same value for authorized, and authenticated.

>     ["vht"] = false, --- rx or tx?

Take any

>     ["wmm"] = false, --- "wme" in iwinfo

Let's keep consistency with the actual format

>     ["aid"] = 0, ---  "Association ID" don't think it's there in iwinfo

let's skip it for mesh interfaces

>     ["mfp"] = false, --- same in iwinfo

ok

>     ["auth"] = true  --- "authenticated" in iwinfo

ok

From the iwinfo output we can also grab:

- signal
- noise

The other parts I think we can skip them for now.
